<a href="https://colab.research.google.com/github/Thadzy/Icanseeyourvoice/blob/main/New_Voice_Train_Thai_Test_Thai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load database



In [ ]:
! pip install -q kaggle

In [ ]:
from google.colab import files

files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"baslasiripatana","key":"433bc7d2a1d608bf5097be88ff82aada"}'}

In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets list

ref                                                                 title                                        size  lastUpdated          downloadCount  voteCount  usabilityRating  
------------------------------------------------------------------  ------------------------------------------  -----  -------------------  -------------  ---------  ---------------  
thedrcat/daigt-v2-train-dataset                                     DAIGT V2 Train Dataset                       29MB  2023-11-16 01:38:36           1973        191  1.0              
muhammadbinimran/housing-price-prediction-data                      Housing Price Prediction Data               763KB  2023-11-21 17:56:32           8855        153  1.0              
everydaycodings/produce-prices-dataset                              Fruits and Vegetables Prices Dataset        232KB  2023-12-11 13:40:33           1457         30  1.0              
thedevastator/books-sales-and-ratings                               Books Sales 

In [ ]:
!kaggle datasets download -d birdy654/deep-voice-deepfake-voice-recognition

100% 3.68G/3.69G [01:58<00:00, 37.0MB/s]
100% 3.69G/3.69G [01:58<00:00, 33.3MB/s]


In [ ]:
!unzip deep-voice-deepfake-voice-recognition.zip

Archive:  deep-voice-deepfake-voice-recognition.zip
  inflating: DEMONSTRATION/DEMONSTRATION/linus-original-DEMO.mp3  
  inflating: DEMONSTRATION/DEMONSTRATION/linus-to-musk-DEMO.mp3  
  inflating: KAGGLE/AUDIO/FAKE/Obama-to-Biden.wav  
  inflating: KAGGLE/AUDIO/FAKE/Obama-to-Trump.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-Obama.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-Trump.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-linus.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-margot.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-musk.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-ryan.wav  
  inflating: KAGGLE/AUDIO/FAKE/biden-to-taylor.wav  
  inflating: KAGGLE/AUDIO/FAKE/linus-to-biden.wav  
  inflating: KAGGLE/AUDIO/FAKE/linus-to-margot.wav  
  inflating: KAGGLE/AUDIO/FAKE/linus-to-musk.wav  
  inflating: KAGGLE/AUDIO/FAKE/linus-to-obama.wav  
  inflating: KAGGLE/AUDIO/FAKE/linus-to-ryan.wav  
  inflating: KAGGLE/AUDIO/FAKE/linus-to-taylor.wav  
  inflating: KAGGLE/AUDIO/FAKE/linu

# Load Test file

In [ ]:
!pip install gdown

In [ ]:
import gdown
import shutil
import os

# Replace 'YOUR_FOLDER_LINK' with the actual shareable link of the folder
folder_link = 'https://drive.google.com/drive/folders/1hJWpn03uZCO_a462L9wE5P6JA-DznxgX'

# Define a destination folder in Colab
destination_folder = '/content/drive/MyDrive/Colab Notebooks/Downloaded_Folder'

# Create the destination folder if it doesn't exist
os.makedirs(destination_folder, exist_ok=True)

# Download the folder using gdown
# gdown.download(folder_link, output=destination_folder, quiet=False)

# Alternatively, if the above method does not work, you can try using gdown.download_folder
gdown.download_folder(folder_link, output=destination_folder, quiet=False)


Retrieving folder list


Retrieving folder 1W557m4nPGYm1UHLeZZbi74OVejbVkyS8 REAL
Processing file 1z73toVpT04oUY_sa7KZ689tu2OaKQaQW babyjingo.mp3
Processing file 1SHOQiIg3C44sEyA5VKgwKsO5lN4lIEq4 BTSstation.mp3
Processing file 1OsA9J0nF-6YDr_9yWaY7N6bRZR4fB5TB CEN.mp3
Processing file 1eoccysrVhthzhicd-Ed8L5EEHlWefOCn CHEFPOM.mp3
Processing file 1-57V9lKN0R9nSaydFkIR9YZfzeus5695 DADOFTHEGYPS.mp3
Processing file 1u3CvRsRBZsKGGw2_1kO2vsas--xItKDF KAYKAI-WOODY.mp3
Processing file 1SQiZb1a88S0UpY2UXjW73nMXv6oV7Su1 kyutae.mp3
Processing file 19XNySQboRuctYV0S2vpOWlEQYvEXPgbu nutapiwich.mp3
Processing file 1lGqQLKwi_jZHdQXbSOHGyc33JbHMB1YE Sample1_Cut.mp3
Processing file 1vJX_E0YhyzjjKcMCqftkXp7uznFSYloK SampleThaiCut2.mp3
Processing file 13ep-vrChnCxmJZeTKRsKLpMEV0m6YLMp SOUNDTISS.mp3
Processing file 1m1skMqi9GaNvDD7ic3MjO-yinL0z1dUi TEDTALK-Pompam.mp3
Processing file 1LawqCCiLt7gTyvRe81pUUIRZsv2DVY4Z THEGYPS.mp3
Processing file 109hOvRhO188I8LYg1tZq1RkyOZ5a0H-n THIRD.mp3
Processing file 1kuoMy5k5_64IH4J9Pn5-bVrPKFw

Retrieving folder list completed
Building directory structure


Access denied with the following error:



 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1z73toVpT04oUY_sa7KZ689tu2OaKQaQW 

Download ended unsuccessfully


# Create Test dataset.csv

In [ ]:
!pip install librosa
!pip install soundfile
!pip install pydub

In [ ]:
from pydub import AudioSegment
import librosa
import numpy as np
import os

def convert_mp3_to_wav(mp3_file_path, output_dir='converted_wav'):
    """
    Converts an MP3 file to WAV format.

    :param mp3_file_path: Path to the MP3 file.
    :param output_dir: Directory where the converted WAV file will be saved.
    :return: Path to the converted WAV file.
    """
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Load MP3 file
    audio = AudioSegment.from_mp3(mp3_file_path)

    # Construct WAV file path
    wav_file_path = os.path.join(output_dir, os.path.basename(mp3_file_path).replace('.mp3', '.wav'))

    # Export as WAV
    audio.export(wav_file_path, format="wav")
    return wav_file_path

def extract_features(wav_file_path):
    """
    Extracts audio features from a WAV file similar to those in the dataset.

    :param wav_file_path: Path to the WAV file.
    :return: Dictionary of extracted features.
    """
    # Load the audio file
    y, sr = librosa.load(wav_file_path)

    # Extract features
    features = {
        'chroma_stft': np.mean(librosa.feature.chroma_stft(y=y, sr=sr)),
        'rms': np.mean(librosa.feature.rms(y=y)),
        'spectral_centroid': np.mean(librosa.feature.spectral_centroid(y=y, sr=sr)),
        'spectral_bandwidth': np.mean(librosa.feature.spectral_bandwidth(y=y, sr=sr)),
        'rolloff': np.mean(librosa.feature.spectral_rolloff(y=y, sr=sr)),
        'zero_crossing_rate': np.mean(librosa.feature.zero_crossing_rate(y))
    }

    # Extract MFCCs
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=20)
    for i, mfcc in enumerate(mfccs):
        features[f'mfcc{i+1}'] = np.mean(mfcc)

    return features

In [ ]:
import csv
import pandas as pd
from pathlib import Path

def process_and_save_to_csv(mp3_file_list, output_csv):
    header = ['chroma_stft', 'rms', 'spectral_centroid', 'spectral_bandwidth',
              'rolloff', 'zero_crossing_rate', 'mfcc1', 'mfcc2', 'mfcc3', 'mfcc4',
              'mfcc5', 'mfcc6', 'mfcc7', 'mfcc8', 'mfcc9', 'mfcc10', 'mfcc11',
              'mfcc12', 'mfcc13', 'mfcc14', 'mfcc15', 'mfcc16', 'mfcc17', 'mfcc18',
              'mfcc19', 'mfcc20', 'LABEL']

    data = []

    for mp3_file in mp3_file_list:
        wav_file = convert_mp3_to_wav(mp3_file)
        features = extract_features(wav_file)

        if mp3_file.parent == Path(dataset_fake_path):
            label = 'FAKE'
        elif mp3_file.parent == Path(dataset_real_path):
            label = 'REAL'
        else:
            label = 'UNKNOWN'  # Adjust as needed

        # Concatenate the values of the dictionary and convert label to a list
        row = np.concatenate([list(features.values()), [label]])
        data.append(row)
        # print(data)
        # print(len(data))
        # print(data[0].shape)
        # print(data[1].shape)
    df = pd.DataFrame(data, columns=header)
    df.to_csv(output_csv, index=False)


# Create dataset.csv

dataset_fake_path = '/content/Thai Dataset/FAKE'
dataset_real_path = '/content/Thai Dataset/REAL'

mp3_files_fake = Path(dataset_fake_path)
mp3_files_real = Path(dataset_real_path)

mp3_file_list_fake = list(mp3_files_fake.glob('*.mp3'))
mp3_file_list_real = list(mp3_files_real.glob('*.mp3'))

mp3_file_lists = mp3_file_list_fake + mp3_file_list_real

output_csv_path = '/content/CSV/thai_test_dataset.csv'

process_and_save_to_csv(mp3_file_lists, output_csv_path)


# Train Model

In [ ]:
import pandas as pd

df = pd.read_csv("/content/CSV/thai_test_dataset.csv")

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

print(X.head(10))
print(y.head(10))

   chroma_stft       rms  spectral_centroid  spectral_bandwidth      rolloff  \
0     0.251850  0.100741        1052.258507          956.591856  1832.247420   
1     0.257549  0.116598        1274.622017         1167.473420  2318.720088   
2     0.343675  0.046268        1331.280849         1253.597596  2373.983811   
3     0.256747  0.082978        1279.501417         1034.379310  2282.448229   
4     0.265698  0.058987        1441.025258         1124.350366  2491.383890   
5     0.358537  0.032508        1442.027011         1228.037112  2649.614829   
6     0.272934  0.090411        1515.576892         1409.558797  2786.011850   
7     0.263140  0.098957        1145.445693         1019.444024  1996.137575   
8     0.269326  0.082873        1436.774785         1364.820742  2850.937983   
9     0.330473  0.069329        1510.763664         1504.920157  2948.557826   

   zero_crossing_rate       mfcc1       mfcc2      mfcc3      mfcc4  ...  \
0            0.059156 -322.132996  101.8149

In [ ]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(y)
y = lb.transform(y)
y = y.ravel()
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50, random_state=1)

from sklearn.model_selection import KFold
kf = KFold(n_splits=5,  shuffle=True, random_state=1)

print(model)
print("KFold splits: " + str(kf.get_n_splits(X)))

RandomForestClassifier(n_estimators=50, random_state=1)
KFold splits: 5


In [ ]:
import time

import numpy as np

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, matthews_corrcoef, roc_auc_score

acc_score = []
prec_score = []
rec_score = []
f1s = []
MCCs = []
ROCareas = []

start = time.time()
for train_index , test_index in kf.split(X):
    X_train , X_test = X.iloc[train_index,:],X.iloc[test_index,:]
    y_train , y_test = y[train_index] , y[test_index]

    model.fit(X_train,y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(pred_values , y_test)
    acc_score.append(acc)

    prec = precision_score(y_test , pred_values, average="binary", pos_label=1)
    prec_score.append(prec)

    rec = recall_score(y_test , pred_values, average="binary", pos_label=1)
    rec_score.append(rec)

    f1 = f1_score(y_test , pred_values, average="binary", pos_label=1)
    f1s.append(f1)

    mcc = matthews_corrcoef(y_test , pred_values)
    MCCs.append(mcc)

    roc = roc_auc_score(y_test , pred_values)
    ROCareas.append(roc)

end = time.time()
timeTaken = (end - start)
print("Model trained in: " + str( round(timeTaken, 2) ) + " seconds.")

Model trained in: 0.45 seconds.


In [ ]:
print("Mean results and (std.):\n")
print("Accuracy: " + str( round(np.mean(acc_score)*100, 3) ) + "% (" + str( round(np.std(acc_score)*100, 3) ) + ")\n")
print("Precision: " + str( round(np.mean(prec_score), 3) ) + " (" + str( round(np.std(prec_score), 3) ) + ")")
print("Recall: " + str( round(np.mean(rec_score), 3) ) + " (" + str( round(np.std(rec_score), 3) ) + ")")
print("F1-Score: " + str( round(np.mean(f1s), 3) ) + " (" + str( round(np.std(f1s), 3) ) + ")")
print("MCC: " + str( round(np.mean(MCCs), 3) ) + " (" + str( round(np.std(MCCs), 3) ) + ")")
print("ROC AUC: " + str( round(np.mean(ROCareas), 3) ) + " (" + str( round(np.std(ROCareas), 3) ) + ")")

Mean results and (std.):

Accuracy: 94.286% (11.429)

Precision: 0.933 (0.133)
Recall: 0.933 (0.133)
F1-Score: 0.933 (0.133)
MCC: 0.883 (0.233)
ROC AUC: 0.942 (0.117)


# Test Thai Dataset

In [ ]:
import pandas as pd

df = pd.read_csv('/content/CSV/thai_test_dataset.csv')

X_thaitest = df.iloc[:,:-1]
y_thaitest = df.iloc[:,-1]

print(X_thaitest.head(10))
print(y_thaitest.head(10))

   chroma_stft       rms  spectral_centroid  spectral_bandwidth      rolloff  \
0     0.251850  0.100741        1052.258507          956.591856  1832.247420   
1     0.257549  0.116598        1274.622017         1167.473420  2318.720088   
2     0.343675  0.046268        1331.280849         1253.597596  2373.983811   
3     0.256747  0.082978        1279.501417         1034.379310  2282.448229   
4     0.265698  0.058987        1441.025258         1124.350366  2491.383890   
5     0.358537  0.032508        1442.027011         1228.037112  2649.614829   
6     0.272934  0.090411        1515.576892         1409.558797  2786.011850   
7     0.263140  0.098957        1145.445693         1019.444024  1996.137575   
8     0.269326  0.082873        1436.774785         1364.820742  2850.937983   
9     0.330473  0.069329        1510.763664         1504.920157  2948.557826   

   zero_crossing_rate       mfcc1       mfcc2      mfcc3      mfcc4  ...  \
0            0.059156 -322.132996  101.8149

In [ ]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(y_thaitest)
y_thaitest = lb.transform(y_thaitest)
y_thaitest = y_thaitest.ravel()
print(y_thaitest)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
pred_values = model.predict(X_thaitest)

In [ ]:
print(pred_values)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
acc_score = []
prec_score = []
rec_score = []
f1s = []
MCCs = []
ROCareas = []

acc = accuracy_score(pred_values , y_thaitest)
acc_score.append(acc)

prec = precision_score(y_thaitest , pred_values, average="binary", pos_label=1)
prec_score.append(prec)

rec = recall_score(y_thaitest , pred_values, average="binary", pos_label=1)
rec_score.append(rec)

f1 = f1_score(y_thaitest , pred_values, average="binary", pos_label=1)
f1s.append(f1)

mcc = matthews_corrcoef(y_thaitest , pred_values)
MCCs.append(mcc)

roc = roc_auc_score(y_thaitest, pred_values)
ROCareas.append(roc)

print("Mean results and (std.):\n")
print("Accuracy: " + str( round(np.mean(acc_score)*100, 3) ) + "% (" + str( round(np.std(acc_score)*100, 3) ) + ")\n")
print("Precision: " + str( round(np.mean(prec_score), 3) ) + " (" + str( round(np.std(prec_score), 3) ) + ")")
print("Recall: " + str( round(np.mean(rec_score), 3) ) + " (" + str( round(np.std(rec_score), 3) ) + ")")
print("F1-Score: " + str( round(np.mean(f1s), 3) ) + " (" + str( round(np.std(f1s), 3) ) + ")")
print("MCC: " + str( round(np.mean(MCCs), 3) ) + " (" + str( round(np.std(MCCs), 3) ) + ")")
print("ROC AUC: " + str( round(np.mean(ROCareas), 3) ) + " (" + str( round(np.std(ROCareas), 3) ) + ")")

Mean results and (std.):

Accuracy: 100.0% (0.0)

Precision: 1.0 (0.0)
Recall: 1.0 (0.0)
F1-Score: 1.0 (0.0)
MCC: 1.0 (0.0)
ROC AUC: 1.0 (0.0)


# Test English Voice

In [ ]:
import pandas as pd

df = pd.read_csv('/content/CSV/eng_test_dataset.csv')

X_thaitest = df.iloc[:,:-1]
y_thaitest = df.iloc[:,-1]

print(X_thaitest.head(10))
print(y_thaitest.head(10))

FileNotFoundError: ignored

In [ ]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(y_thaitest)
y_thaitest = lb.transform(y_thaitest)
y_thaitest = y_thaitest.ravel()
print(y_thaitest)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [ ]:
pred_values = model.predict(X_thaitest)

In [ ]:
print(pred_values)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]


# Save Model

In [ ]:
import os
import joblib
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

In [ ]:
joblib.dump(model, "./random_forest_v2.joblib")

['./random_forest_v2.joblib']

# Test Siri voice

In [ ]:
test_file = '/content/Siri.mp3'
wav_file = convert_mp3_to_wav(test_file)
features = extract_features(wav_file)

In [ ]:
features

{'chroma_stft': 0.28753564,
 'rms': 0.057386935,
 'spectral_centroid': 1686.270227818574,
 'spectral_bandwidth': 1316.7305970380958,
 'rolloff': 2943.050537109375,
 'zero_crossing_rate': 0.11184488932291667,
 'mfcc1': -370.54288,
 'mfcc2': 107.30291,
 'mfcc3': -9.483347,
 'mfcc4': 17.231188,
 'mfcc5': -5.7565355,
 'mfcc6': -4.1298466,
 'mfcc7': -12.382151,
 'mfcc8': -7.7946477,
 'mfcc9': -13.003581,
 'mfcc10': -7.9390373,
 'mfcc11': -11.80506,
 'mfcc12': 0.13583872,
 'mfcc13': -5.168755,
 'mfcc14': 2.8077614,
 'mfcc15': -2.0708346,
 'mfcc16': -2.1977654,
 'mfcc17': 3.4606993,
 'mfcc18': -4.098655,
 'mfcc19': 0.5016587,
 'mfcc20': -6.298322}

In [ ]:
features_list = list(features.values())
pred_values = model.predict([features_list])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
pred_values

array([1])

# Test Thai Fake mp4


In [ ]:
test_file = '/content/Thai_Dataset/FAKE/การเปลี่ยนแปลงคือหัวใจของการเต....mp3'
wav_file = convert_mp3_to_wav(test_file)
features = extract_features(wav_file)

In [ ]:
features_list = list(features.values())
pred_values = model.predict([features_list])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
pred_values

array([0])

# Test Thai Real mp4

In [ ]:
test_file = '/content/Thai_Dataset/REAL/CEN.mp3'
wav_file = convert_mp3_to_wav(test_file)
features = extract_features(wav_file)

In [ ]:
features_list = list(features.values())
pred_values = model.predict([features_list])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
type([features_list])
len([features_list][0])

26

In [ ]:
pred_values

array([1])

# Test present fake

In [ ]:
test_file = '/content/FAKE_TEST_CUT.mp3'
wav_file = convert_mp3_to_wav(test_file)
features = extract_features(wav_file)

In [ ]:
features_list = list(features.values())
pred_values = model.predict([features_list])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
pred_values

array([0])

# Test present real

In [ ]:
test_file = '/content/REAL_TEST_CUT.mp3'
wav_file = convert_mp3_to_wav(test_file)
features = extract_features(wav_file)

In [ ]:
features_list = list(features.values())
pred_values = model.predict([features_list])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
pred_values

array([1])